site_name: Intro to Machine Learning
site_author: 'Vinay Krishna'
site_url: 'https://vinkrish.github.io/MachineLearning/'
theme:
  name: 'material'
  
# Repository
repo_name: 'vinkrish/MachineLearning'
repo_url: 'https://github.com/vinkrish/MachineLearning'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/vinkrish'

extra_javascript:
  # Add MathJax support
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML'

markdown_extensions:
  - mdx_math

# Navigation
nav:
  - About: index.md
  - Math: math.md
  - Libraries: libraries.md
  - Workflow: ml_workflow.md
  - Algorithms: 
    - Logistic Regression: logistic_regression.md
    - Neural Network: neural_network.md
    - Definition: algorithms.md
  - Deep Learning:
    - Intro: deep_learning.md
    - Reinforcement Learning: reinforcement_learning.md
    - Dynamic Programming: dynamic_programming.md
    - Monte Carlo Methods: monte_carlo_methods.md
    - Temporal Difference Methods: temporal_difference_methods.md
    - Summary: rl_summary.md
    - Applications: applications.md
  - Data Science:
    - Intro: data_science.md
    - Data Analysis Process: dap.md
  - Big Data: big_data.md
  - TensorFlow: tensorflow.md
  - Terminology: terminology.md
  - Source: source.md