site_name: Machine Learning
site_author: 'Vinay Krishna'
site_url: 'https://vinkrish.github.io/MachineLearning/'
theme:
  name: 'material'
  
# Repository
repo_name: 'vinkrish/MachineLearning'
repo_url: 'https://github.com/vinkrish/MachineLearning'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/vinkrish'

extra_javascript:
  # Add MathJax support
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'

# Navigation
nav:
  - About: index.md
  - Terminology: terminology.md
  - Math: math.md
  - Algorithms: algorithms.md
  - Data Analysis Process: dap.md
  - Machine Learning Workflow: ml_workflow.md
  - TensorFlow: tensorflow.md
  # - Andrew Ng's ML Course:
  #   - Week 1:
  #     - Model Representation: week_1/model_representation.md
  #     - Cost Function: week_1/cost_function.md
  #     - Cost Function Intuition 1: week_1/cost_function_intuition_1.md
  #     - Cost Function Intuition 2: week_1/cost_function_intuition_2.md
  #     - Gradient Descent: week_1/gradient_descent.md
  #     - Gradient Descent Intuition: week_1/gradient_descent_intuition.md
  #     - Gradient Descent For Linear Regression: week_1/gd_for_linear_regression.md
  - Source: source.md